import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/src/components/header/Header";
import StoreProvider from "@/src/components/provider/StoreProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Next-js Project",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
      <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
        <Header/>
        {children}
        </body>
      </StoreProvider>
      </html>
  );
}
